import mongoose from 'mongoose';

const googleConnectionSchema = new mongoose.Schema({
  // 🔐 Primary key (auto-generated by MongoDB)
  // _id: ObjectId (implicit)

  // 👤 Connection owner
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required'],
    index: true
  },

  // 📌 Project association
  project_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SeoProject',
    required: [true, 'Project ID is required'],
    index: true
  },

  // 🎯 Connection purpose
  purpose: {
    type: String,
    required: [true, 'Purpose is required'],
    enum: ['google_visibility'],
    default: 'google_visibility'
  },

  // � Google services enabled for this connection
  service_type: {
    type: [String],
    enum: ['search_console', 'analytics', 'business_profile'],
    default: [],
    validate: {
      validator: function(serviceTypes) {
        // Ensure no duplicates
        return serviceTypes.length === new Set(serviceTypes).size;
      },
      message: 'Service types must be unique'
    }
  },

  // 🔄 Last successful data sync timestamp
  last_sync_at: {
    type: Date,
    default: null
  },

  // 📊 Analytics property ID (required when analytics service is enabled)
  analytics_property_id: {
    type: String,
    required: false, // Only required when analytics service is enabled
    validate: {
      validator: function(v) {
        // If analytics is enabled, property_id must be present and non-empty
        if (this.service_type && this.service_type.includes('analytics')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Analytics property ID is required when Analytics service is enabled'
    },
    trim: true
  },

  // 🏢 Business Profile Account ID (required when business_profile service is enabled)
  business_account_id: {
    type: String,
    required: false, // Only required when business_profile service is enabled
    validate: {
      validator: function(v) {
        // If business_profile is enabled, account_id must be present and non-empty
        if (this.service_type && this.service_type.includes('business_profile')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Business Profile account ID is required when Business Profile service is enabled'
    },
    trim: true
  },

  // 📍 Business Profile Location ID (required when business_profile service is enabled)
  business_location_id: {
    type: String,
    required: false, // Only required when business_profile service is enabled
    validate: {
      validator: function(v) {
        // If business_profile is enabled, location_id must be present and non-empty
        if (this.service_type && this.service_type.includes('business_profile')) {
          return v && v.trim().length > 0;
        }
        return true;
      },
      message: 'Business Profile location ID is required when Business Profile service is enabled'
    },
    trim: true
  },

  // 💾 Business Profile Account Cache (prevent repeated API calls)
  business_accounts_cache: {
    type: Array,
    default: []
  },

  business_accounts_cached_at: {
    type: Date,
    default: null
  },

  // � Google OAuth tokens
  refresh_token: {
    type: String,
    required: [true, 'Refresh token is required'],
    index: true
  },

  access_token: {
    type: String,
    default: null
  },

  token_expires_at: {
    type: Date,
    default: null
  },

  // 👤 Google account information
  google_email: {
    type: String,
    required: [true, 'Google email is required'],
    lowercase: true,
    trim: true
  },

  google_name: {
    type: String,
    required: [true, 'Google name is required'],
    trim: true
  },

  google_avatar: {
    type: String,
    default: null
  },

  // ⏰ Timestamps
  connected_at: {
    type: Date,
    default: Date.now
  },

  last_used_at: {
    type: Date,
    default: null
  },

  // 📊 Connection status
  status: {
    type: String,
    enum: ['active', 'revoked', 'expired'],
    default: 'active',
    index: true
  }

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Compound unique index on user_id, project_id, and purpose
googleConnectionSchema.index({ user_id: 1, project_id: 1, purpose: 1 }, { unique: true });

// Index for status filtering
googleConnectionSchema.index({ status: 1 });

// Index for user connections
googleConnectionSchema.index({ user_id: 1, status: 1 });

// Index for project connections
googleConnectionSchema.index({ project_id: 1, status: 1 });

// Static method to find active connection
googleConnectionSchema.statics.findActiveConnection = async function(userId, projectId, purpose = 'google_visibility') {
  return await this.findOne({
    user_id: userId,
    project_id: projectId,
    purpose: purpose,
    status: 'active'
  }).populate('user_id', 'email firstName lastName')
    .populate('project_id', 'project_name main_url');
};

// Static method to revoke connection
googleConnectionSchema.statics.revokeConnection = async function(userId, projectId, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active'
    },
    {
      status: 'revoked',
      updated_at: new Date()
    }
  );
};

// Static method to update service types
googleConnectionSchema.statics.updateServiceTypes = async function(userId, projectId, serviceTypes, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active'
    },
    {
      service_type: serviceTypes,
      updated_at: new Date()
    },
    { upsert: false }
  );
};

// Static method to update last sync timestamp
googleConnectionSchema.statics.updateLastSync = async function(userId, projectId, serviceType, purpose = 'google_visibility') {
  return await this.updateOne(
    {
      user_id: userId,
      project_id: projectId,
      purpose: purpose,
      status: 'active',
      service_type: serviceType
    },
    {
      last_sync_at: new Date(),
      updated_at: new Date()
    }
  );
};

// Static method to find connections by service type
googleConnectionSchema.statics.findByServiceType = async function(serviceType, purpose = 'google_visibility') {
  return await this.find({
    purpose: purpose,
    service_type: serviceType,
    status: 'active'
  }).populate('user_id', 'email firstName lastName')
    .populate('project_id', 'project_name main_url');
};

// Ensure virtuals are included in JSON output
googleConnectionSchema.set('toJSON', { virtuals: true });
googleConnectionSchema.set('toObject', { virtuals: true });

const GoogleConnection = mongoose.model('GoogleConnection', googleConnectionSchema);
export default GoogleConnection;
