import mongoose from 'mongoose';

const seoProjectSchema = new mongoose.Schema({
  // 🔐 Primary key (auto-generated by MongoDB)
  // _id: ObjectId (implicit)

  // 👤 Project owner
  user_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: [true, 'User ID is required'],
    index: true
  },

  // 📌 Project Information
  project_name: {
    type: String,
    required: [true, 'Project name is required'],
    trim: true,
    minlength: [3, 'Project name must be at least 3 characters long'],
    maxlength: [100, 'Project name cannot exceed 100 characters'],
    match: [/^[a-zA-Z0-9\s\-_]+$/, 'Project name can only contain letters, numbers, spaces, hyphens, and underscores']
  },
  
  main_url: {
    type: String,
    required: [true, 'Main URL is required'],
    trim: true,
    lowercase: true,
    validate: {
      validator: function(url) {
        const urlRegex = /^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}(?:[-a-zA-Z0-9()@:%_\+.~#?&//=]*)$/;
        return urlRegex.test(url);
      },
      message: 'Please provide a valid URL starting with http:// or https://'
    }
  },

  business_type: {
    type: String,
    trim: true,
    maxlength: [200, 'Business type cannot exceed 200 characters'],
    default: null
  },

  industry: {
    type: String,
    trim: true,
    maxlength: [100, 'Industry cannot exceed 100 characters'],
    default: null
  },

  // 🌍 Location & Language
  location: {
    type: String,
    trim: true,
    maxlength: [200, 'Location cannot exceed 200 characters'],
    default: null
  },

  country: {
    type: String,
    default: 'US',
    uppercase: true,
    minlength: 2,
    maxlength: 2
  },

  language: {
    type: String,
    default: 'en',
    lowercase: true,
    minlength: 2,
    maxlength: 5
  },

  // ⚙️ Status & Scheduling
  status: {
    type: String,
    enum: ['draft', 'active', 'paused', 'error'],
    default: 'draft',
    index: true
  },

  scrape_frequency: {
    type: String,
    enum: ['manual', 'daily', 'weekly', 'monthly'],
    default: 'manual'
  },

  last_scraped_at: {
    type: Date,
    default: null
  },

  audit_started_at: {
    type: Date,
    default: null
  },

  last_analysis_at: {
    type: Date,
    default: null
  },

  // 🎯 SINGLE SOURCE OF TRUTH: Audit duration calculated from lifecycle timestamps
  audit_duration_ms: {
    type: Number,
    default: 0,
    min: 0 // Ensure non-negative duration
  },

  // 📊 SEO/Scraping Configuration
  keywords: {
    type: [String],
    required: [true, 'At least one keyword is required'],
    validate: {
      validator: function(keywords) {
        return keywords.length >= 1;
      },
      message: 'At least one keyword is required'
    }
  },

  description: {
    type: String,
    trim: true,
    maxlength: [500, 'Description cannot exceed 500 characters']
  },

  // 📊 Aggregated Metrics (Updated by workers only)
  total_pages: {
    type: Number,
    default: 0,
    min: 0
  },

  total_issues: {
    type: Number,
    default: 0,
    min: 0
  },

  // 📊 Detailed Crawl Metrics (NEW - from crawl summary)
  pages_discovered: {
    type: Number,
    default: 0,
    min: 0
  },

  pages_crawled: {
    type: Number,
    default: 0,
    min: 0
  },

  pages_analyzed: {
    type: Number,
    default: 0,
    min: 0
  },

  crawl_duration: {
    type: Number,
    default: 0,
    min: 0
  },

  crawl_success_rate: {
    type: Number,
    default: 0,
    min: 0,
    max: 100
  },

  crawl_status: {
    type: String,
    enum: ['pending', 'running', 'completed', 'failed', 'cancelled'],
    default: 'pending'
  },

  last_crawl_summary: {
    type: Object,
    default: null
  },

  // 🤖 AI Visibility Data (Updated by AI visibility scoring worker)
  ai_visibility: {
    score: {
      type: Number
    },
    pages_scored: {
      type: Number
    },
    categories: {
      type: Object,
      default: {}
    },
    scoring_version: {
      type: String
    },
    summary: {
      type: String
    }
  },

  last_ai_analysis_at: {
    type: Date,
    default: null
  },

  // 🕒 System Timestamps (auto-managed by Mongoose)
  // created_at: Date (implicit)
  // updated_at: Date (implicit)

  // 🏢 Verified Business Information (from Google Places API)
  verified_business: {
    placeId: {
      type: String,
      required: false
    },
    name: {
      type: String,
      required: false
    },
    address: {
      type: String,
      required: false
    },
    website: {
      type: String,
      required: false
    },
    phone: {
      type: String,
      required: false
    },
    rating: {
      type: Number,
      required: false,
      min: 0,
      max: 5
    },
    location: {
      lat: {
        type: Number,
        required: false
      },
      lng: {
        type: Number,
        required: false
      }
    },
    verifiedAt: {
      type: Date,
      required: false
    }
  },

  // Project source tracking
  source: {
    type: String,
    enum: ['web', 'external', 'api', 'migration'],
    default: 'web'
  }

}, {
  timestamps: { createdAt: 'created_at', updatedAt: 'updated_at' }
});

// Compound unique index on user_id and project_name
seoProjectSchema.index({ user_id: 1, project_name: 1 }, { unique: true });

// Index for status filtering
seoProjectSchema.index({ status: 1 });

// Index for created_at sorting
seoProjectSchema.index({ created_at: -1 });

// Index for scraping fields
seoProjectSchema.index({ last_scraped_at: -1 });
seoProjectSchema.index({ user_id: 1, last_scraped_at: -1 });
seoProjectSchema.index({ scrape_frequency: 1 });

// Index for crawl status and timing (NEW)
seoProjectSchema.index({ crawl_status: 1 });
seoProjectSchema.index({ audit_started_at: -1 });
seoProjectSchema.index({ last_analysis_at: -1 });
seoProjectSchema.index({ crawl_duration: -1 });
seoProjectSchema.index({ audit_duration_ms: -1 }); // 🎯 SINGLE SOURCE OF TRUTH INDEX

// Index for AI visibility analysis timing
seoProjectSchema.index({ last_ai_analysis_at: -1 });

// Index for business/industry filtering
seoProjectSchema.index({ industry: 1 });
seoProjectSchema.index({ country: 1 });
seoProjectSchema.index({ language: 1 });

// Pre-save middleware to process keywords
seoProjectSchema.pre('save', function(next) {
  if (this.keywords && this.keywords.length > 0) {
    // Trim keywords and remove duplicates
    this.keywords = [...new Set(this.keywords.map(keyword => keyword.trim()).filter(keyword => keyword.length >= 2))];
  }
  next();
});

// Virtual for keyword count
seoProjectSchema.virtual('keyword_count', {
  get: function() {
    return (this.keywords || []).length;
  }
});

// Virtual for project age
seoProjectSchema.virtual('project_age_days', {
  get: function() {
    return Math.floor((Date.now() - this.created_at.getTime()) / (1000 * 60 * 60 * 24));
  }
});

// Virtual for days since last scrape
seoProjectSchema.virtual('days_since_last_scrape', {
  get: function() {
    if (!this.last_scraped_at) return null;
    return Math.floor((Date.now() - this.last_scraped_at.getTime()) / (1000 * 60 * 60 * 24));
  }
});

// Static method to update scraping results (worker-only)
seoProjectSchema.statics.updateScrapingResults = async function(projectId, results) {
  try {
    const updateData = {
      last_scraped_at: new Date(),
      total_pages: results.total_pages || 0,
      total_issues: results.total_issues || 0,
      updated_at: new Date()
    };

    return await this.findByIdAndUpdate(projectId, updateData, { new: true });
  } catch (error) {
    console.error('Error updating scraping results:', error);
    throw error;
  }
};

// Static method to get project scraping summary
seoProjectSchema.statics.getScrapingSummary = async function(projectId) {
  try {
    const project = await this.findById(projectId)
      .select('project_name main_url business_type industry location country language status scrape_frequency last_scraped_at total_pages total_issues created_at updated_at keyword_count')
      .lean();
    
    return project;
  } catch (error) {
    console.error('Error getting scraping summary:', error);
    throw error;
  }
};

// Static method to get projects by scraping frequency
seoProjectSchema.statics.getProjectsByFrequency = function(frequency) {
  return this.find({ scrape_frequency: frequency })
    .sort({ last_scraped_at: -1 })
    .populate('user_id', 'name email');
};

// Static method to get projects needing scraping
seoProjectSchema.statics.getProjectsNeedingScrape = function() {
  const oneWeekAgo = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  
  return this.find({
    status: 'active',
    scrape_frequency: { $ne: 'manual' },
    $or: [
      { last_scraped_at: { $lt: oneWeekAgo } },
      { last_scraped_at: null }
    ]
  }).sort({ last_scraped_at: 1, created_at: 1 });
};

// Ensure virtuals are included in JSON output
seoProjectSchema.set('toJSON', { virtuals: true });
seoProjectSchema.set('toObject', { virtuals: true });

const SeoProject = mongoose.model('SeoProject', seoProjectSchema);
export default SeoProject;
